// Autogenerated from Pigeon (v10.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SDKHostApi {
  func initializeSDK(key: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SDKHostApiSetup {
  /// The codec used by SDKHostApi.
  /// Sets up an instance of `SDKHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SDKHostApi?) {
    let initializeSDKChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.SDKHostApi.initializeSDK", binaryMessenger: binaryMessenger)
    if let api = api {
      initializeSDKChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          try api.initializeSDK(key: keyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeSDKChannel.setMessageHandler(nil)
    }
  }
}
